apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/jacky9999999/hello.git
  labels:
    app: hello
    app.kubernetes.io/component: hello
    app.kubernetes.io/instance: hello
    app.kubernetes.io/name: hello
    app.kubernetes.io/part-of: hello
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
  name: hello
spec:
  lookupPolicy:
    local: false
